"""Alle deutschen Flughäfen mit regulärem Passagierverkehr."""
from __future__ import annotations

GERMAN_AIRPORTS = [
    {"iata": "BER", "name": "Berlin Brandenburg", "city": "Berlin"},
    {"iata": "BRE", "name": "Bremen", "city": "Bremen"},
    {"iata": "CGN", "name": "Köln Bonn", "city": "Köln"},
    {"iata": "DRS", "name": "Dresden", "city": "Dresden"},
    {"iata": "DTM", "name": "Dortmund", "city": "Dortmund"},
    {"iata": "DUS", "name": "Düsseldorf", "city": "Düsseldorf"},
    {"iata": "ERF", "name": "Erfurt-Weimar", "city": "Erfurt"},
    {"iata": "FDH", "name": "Friedrichshafen", "city": "Friedrichshafen"},
    {"iata": "FKB", "name": "Karlsruhe/Baden-Baden", "city": "Karlsruhe"},
    {"iata": "FMM", "name": "Memmingen Allgäu", "city": "Memmingen"},
    {"iata": "FMO", "name": "Münster Osnabrück", "city": "Münster"},
    {"iata": "FRA", "name": "Frankfurt am Main", "city": "Frankfurt"},
    {"iata": "GWT", "name": "Sylt", "city": "Westerland"},
    {"iata": "HAJ", "name": "Hannover-Langenhagen", "city": "Hannover"},
    {"iata": "HAM", "name": "Hamburg", "city": "Hamburg"},
    {"iata": "HHN", "name": "Frankfurt-Hahn", "city": "Hahn"},
    {"iata": "KEL", "name": "Kiel-Holtenau", "city": "Kiel"},
    {"iata": "LEJ", "name": "Leipzig/Halle", "city": "Leipzig"},
    {"iata": "LBC", "name": "Lübeck", "city": "Lübeck"},
    {"iata": "MUC", "name": "München", "city": "München"},
    {"iata": "NRN", "name": "Weeze Niederrhein", "city": "Weeze"},
    {"iata": "NUE", "name": "Nürnberg", "city": "Nürnberg"},
    {"iata": "PAD", "name": "Paderborn Lippstadt", "city": "Paderborn"},
    {"iata": "SCN", "name": "Saarbrücken", "city": "Saarbrücken"},
    {"iata": "STR", "name": "Stuttgart", "city": "Stuttgart"},
]

# Mapping IATA → Zug-Zielstadt (für Zugsuche Braunschweig → Flughafen)
AIRPORT_TRAIN_CITY: dict[str, str] = {
    "BER": "Berlin",
    "BRE": "Bremen",
    "CGN": "Köln",
    "DRS": "Dresden",
    "DTM": "Dortmund",
    "DUS": "Düsseldorf",
    "ERF": "Erfurt",
    "FDH": "Friedrichshafen",
    "FKB": "Karlsruhe",
    "FMM": "Memmingen",
    "FMO": "Münster",
    "FRA": "Frankfurt",
    "GWT": "Westerland",
    "HAJ": "Hannover",
    "HAM": "Hamburg",
    "HHN": "Frankfurt",
    "KEL": "Kiel",
    "LEJ": "Leipzig",
    "LBC": "Lübeck",
    "MUC": "München",
    "NRN": "Kevelaer",
    "NUE": "Nürnberg",
    "PAD": "Paderborn",
    "SCN": "Saarbrücken",
    "STR": "Stuttgart",
}
